import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import type { MiddlewareContext, MiddlewareResult } from './middlewareContext';

const MALICIOUS_PATH_PATTERNS = [
  /\/fckeditor/i,
  /\/tiny_mce/i,
  /\/tinymce/i,
  /\/phpmyadmin/i,
  /\/pma\//i,
  /\/mysql\//i,
  /\/jmx-console/i,
  /\/web-console/i,
  /\/axis2/i,
  /\/axis\//i,
  /\/jolokia/i,
  /\/faces\//i,
  /\/scripts\//i,
  /\/cgi-bin\//i,
  /\/msdac/i,
  /\/_vti_bin/i,
  /\/citrix/i,
  /\/node\/1\?_format=hal_json/i,
  /\/zabbix\.php/i,
  /\/mantis/i,
  /\/mantisbt/i,
  /\/remote\/fgt_lang/i,
  /\/wavemaker/i,
  /\/docpicker/i,
  /\/sugarcrm/i,
  /\/telerik/i,
  /\/wps\//i,
  /\/resolute\.php/i,
  /\/console\/login/i,
  /\/wp-content\//i,
  /\/wp-admin/i,
  /\/wp-login/i,
  /\/\.git/i,
  /\/\.svn/i,
  /\/\.env/i,
  /\/debug\//i,
  /\/actuator/i,
  /\/heapdump/i,
  /\/status\?full/i,
  /\/AdaptCMS/i,
  /\/ADSearch/i,
  /\/analytics\/saw/i,
  /\/bmc_help/i,
  /\/bugs\/verify/i,
  /\/CTCWebService/i,
  /\/CgiStart/i,
  /\/application\.wadl/i,
  /\/service\?wsdl/i,
  /\/names\.nsf/i,
  /\/filter\/jmol/i,
  /\/getFavicon/i,
  /\/gotoURL/i,
  /\/open-flash-chart/i,
  /\/PDC/i,
  /\/show_image_/i,
  /\/proxy\.stream/i,
  /\/plugins\/servlet\/gadgets/i,
  /\/WebResource\.axd/i,
  /\/Telerik\.Web\.UI/i,
  /\/secure\/ConfigurePortal/i,
  /\/servlet\/taskProc/i,
  /\/MicroStrategy/i,
] as RegExp[];

export function filterMaliciousPaths(_request: NextRequest, ctx: MiddlewareContext): MiddlewareResult {
  if (MALICIOUS_PATH_PATTERNS.some((pattern) => pattern.test(ctx.pathname))) {
    return new NextResponse('Not Found', { status: 404 });
  }
  return null;
}
